// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_Practice2024.Models;

public partial class Demand_Apartment
{
    public int IdApartament { get; set; }

    public double? MinArea { get; set; }

    public double? MaxArea { get; set; }

    public int? MinRooms { get; set; }

    public int? MaxRooms { get; set; }

    public int? MinFloor { get; set; }

    public int? MaxFloor { get; set; }

    public virtual ICollection<Demand> Demands { get; set; } = new List<Demand>();
}